import LessonPage from '../../layout/LessonPage';
import ChartFrame from '../../ui/ChartFrame';
import ChartFamilyLesson, { type ChartSpec } from './ChartFamilyLesson';
import { Info, Target, Zap, TrendingUp } from 'lucide-react';
import {
    GanttMini,
    ControlChartMini,
    FunnelMini,
    RadarMini,
    GaugeMini,
} from '../../charts/demos/MiniCharts';

const charts: ChartSpec[] = [
    {
        slug: 'gantt',
        name: 'Gantt Chart',
        whenToUse: [
            'Project scheduling and timeline visualization showing task start dates, durations, and dependencies',
            'Resource allocation dashboards where overlapping tasks reveal capacity conflicts',
            'Communicating project status to stakeholders who need to see schedule at a glance',
        ],
        whenNotToUse: [
            'Very long time horizons with many tasks — granularity becomes unreadable',
            'Agile workflows where tasks are too fluid to represent as fixed bars',
            'When the critical path or task dependencies are the primary analytical focus — PERT/network is better',
        ],
        interpretationRisk: 'Gantt charts show planned duration but not completion percentage or quality. A task that appears "on time" as a full bar may be 0% complete internally. Without explicit progress overlays, Gantt charts are optimistic by default.',
        cognitiveRef: 'Pre-attentive: length, position (time)',
        ethicalRef: 'Risk: Planned vs. actual confusion',
        demo: <GanttMini />,
    },
    {
        slug: 'control-chart',
        name: 'Control Chart (SPC)',
        whenToUse: [
            'Statistical Process Control: monitoring whether a process is in control or exhibiting special-cause variation',
            'Manufacturing, quality assurance, or service delivery metrics tracked over time',
            'When distinguishing common-cause (random) variation from special-cause (assignable) variation is critical',
        ],
        whenNotToUse: [
            'Data that is not generated by a stable, repeating process',
            'Small samples where control limits cannot be reliably estimated (< 20 historical data points)',
            'Audiences who will interpret the ±3σ limits as performance targets rather than statistical boundaries',
        ],
        interpretationRisk: 'Control limits (±3σ) are statistical bounds for random variation, not performance targets. Communicating UCL/LCL to business audiences who interpret them as "acceptable range" goals corrupts the method — processes will be "managed to the limits" rather than continuously improved.',
        cognitiveRef: 'Pre-attentive: position, color (alert)',
        ethicalRef: 'Risk: Limits as targets',
        demo: <ControlChartMini />,
    },
    {
        slug: 'funnel',
        name: 'Funnel Chart',
        whenToUse: [
            'Sequential conversion or qualification processes where each stage filters the population from the previous',
            'Sales pipeline, marketing attribution, or user activation flows with defined sequential stages',
            'When identifying the stage with the largest drop-off is the primary analytical goal',
        ],
        whenNotToUse: [
            'Non-sequential processes where items can enter or exit at any stage',
            'When the total population at each stage is more important than the ratio between stages',
            'Processes with feedback loops — funnels imply strictly linear, forward-only flow',
        ],
        interpretationRisk: 'Funnel charts imply that all items enter at the top stage. In real pipelines, leads often enter mid-funnel, skip stages, or recycle through earlier stages. A funnel that makes a 30% overall conversion rate look visually impressive may hide a catastrophic early-stage drop-off.',
        cognitiveRef: 'Pre-attentive: length (width)',
        ethicalRef: 'Risk: Entry assumption',
        demo: <FunnelMini />,
    },
    {
        slug: 'radar',
        name: 'Radar / Spider Chart',
        whenToUse: [
            'Comparing performance profiles across 5–8 dimensions for 2–3 entities simultaneously',
            'Communicating trade-off profiles where no single axis dominates (e.g., risk-return across asset classes)',
            'Qualitative scoring rubrics where the "shape" of the profile is the primary insight',
        ],
        whenNotToUse: [
            'More than 3 overlapping polygons — the center fills with color and all shapes blur together',
            'When individual axis values need to be read precisely — the radial scale is hard to decode',
            'Axes with different units or scales that are not meaningfully comparable',
        ],
        interpretationRisk: 'The area of the radar polygon is extremely sensitive to axis ordering. Two identical datasets with axes reordered produce different polygon shapes and areas, suggesting different "performance" even though no values changed. Axis order should be theoretically motivated, not arbitrary.',
        cognitiveRef: 'Pre-attentive: area, shape',
        ethicalRef: 'Risk: Axis ordering changes area',
        demo: <RadarMini />,
    },
    {
        slug: 'gauge',
        name: 'Gauge / Dial Chart',
        whenToUse: [
            'Single KPI display in an executive dashboard where the metaphor of "progress toward a target" is intuitive',
            'When three qualitative performance zones (red/amber/green) need to be visible with the current value',
            'Physical monitoring contexts where users are already familiar with dial metaphors (speed, pressure)',
        ],
        whenNotToUse: [
            'Analytical reporting — gauges use space inefficiently and convey one number a bar could show better',
            'Multiple KPIs side-by-side — comparisons between gauges require mental effort that a table eliminates',
            'When historical trend matters — the gauge is a point-in-time reading with no trend context',
        ],
        interpretationRisk: 'Gauge charts show a single value in a half-circle that uses roughly 50% more space than a bullet chart showing the same information. They are frequently used in dashboards to make reports appear more sophisticated while actually reducing information density and analytical clarity.',
        cognitiveRef: 'Pre-attentive: angle, position',
        ethicalRef: 'Risk: Space-to-information inefficiency',
        demo: <GaugeMini />,
    },
];


// Gauge vs Bullet comparison chart
function GaugeVsBulletChart() {
    const value = 73, target = 80;

    // Gauge arc
    const cx = 50, cy = 48, r = 35;
    const arcAngle = (v: number) => ((v / 100) * Math.PI) + Math.PI; // left to right
    const toArcX = (a: number) => cx + r * Math.cos(a);
    const toArcY = (a: number) => cy + r * Math.sin(a);

    const startAngle = Math.PI; // 180°
    const valueAngle = arcAngle(value);
    const targetAngle = arcAngle(target);
    const aX = toArcX(valueAngle);
    const aY = toArcY(valueAngle);
    const bX = toArcX(startAngle);
    const bY = toArcY(startAngle);
    const endX = toArcX(0); // right side

    // Background arc (grey)
    const bgPath = `M ${bX} ${bY} A ${r} ${r} 0 0 1 ${endX} ${cy}`;
    // Value arc (green)
    const valPath = `M ${bX} ${bY} A ${r} ${r} 0 0 1 ${aX} ${aY}`;

    return (
        <ChartFrame
            label="Density Conflict: Gauge vs. Bullet"
            note="Both charts encode identical data: Actual (73%), Target (80%), and performance zones. The bullet chart offers superior spatial economy and higher decoding accuracy."
        >
            <div className="p-6 bg-stone-50/30">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                    {/* Gauge Side */}
                    <div className="space-y-4">
                        <div className="text-center">
                            <span className="text-[10px] font-black text-stone-400 uppercase tracking-widest">
                                Gauge: Meter Metaphor
                            </span>
                        </div>
                        <div className="bg-white rounded-xl border border-stone-100 p-6 shadow-sm flex items-center justify-center h-32">
                            <svg viewBox="0 0 480 220" className="w-full max-w-[160px] drop-shadow-sm">
                                <path d={bgPath} fill="none" stroke="#e7e5e4" strokeWidth={10} strokeLinecap="round" />
                                <path d={valPath} fill="none" stroke="#10b981" strokeWidth={10} strokeLinecap="round" />
                                <line
                                    x1={cx + (r - 8) * Math.cos(targetAngle)}
                                    y1={cy + (r - 8) * Math.sin(targetAngle)}
                                    x2={cx + (r + 2) * Math.cos(targetAngle)}
                                    y2={cy + (r + 2) * Math.sin(targetAngle)}
                                    stroke="#1e293b" strokeWidth={2.5} />
                                <text x={cx} y={cy + 8} fill="#059669" fontSize={14} textAnchor="middle">{value}%</text>
                            </svg>
                        </div>
                        <ul className="space-y-1.5 px-2">
                            {[
                                { text: 'Uses +60% more vertical space', type: 'bad' },
                                { text: 'Low-accuracy angle encoding', type: 'bad' },
                                { text: 'Visual "noise" from heavy arcs', type: 'neutral' },
                            ].map((l, i) => (
                                <li key={i} className="flex items-center gap-2 text-[11px] text-stone-500 font-medium">
                                    <div className={`w-1 h-1 rounded-full ${l.type === 'bad' ? 'bg-rose-400' : 'bg-stone-300'}`} />
                                    {l.text}
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Bullet Side */}
                    <div className="space-y-4">
                        <div className="text-center">
                            <span className="text-[10px] font-black text-stone-400 uppercase tracking-widest">
                                Bullet: High Density
                            </span>
                        </div>
                        <div className="bg-white rounded-xl border border-stone-100 p-6 shadow-sm flex items-center justify-center h-32">
                            <svg viewBox="0 0 480 220" className="w-full max-w-[160px] drop-shadow-sm">
                                <rect x={0} y={20} width={100} height={20} fill="#f5f5f4" rx={2} />
                                <rect x={0} y={20} width={80} height={20} fill="#e7e5e4" rx={2} />
                                <rect x={0} y={20} width={60} height={20} fill="#d6d3d1" rx={2} />
                                <rect x={0} y={24} width={value} height={12} fill="#10b981" rx={1.5} />
                                <line x1={target} y1={16} x2={target} y2={44} stroke="#1e293b" strokeWidth={3} />
                                <text x={value + 4} y={34} fill="#065f46" fontSize={8}>{value}%</text>
                                <text x={target} y={12} fill="#1e293b" fontSize={7} textAnchor="middle">GOAL</text>
                            </svg>
                        </div>
                        <ul className="space-y-1.5 px-2">
                            {[
                                { text: 'High-accuracy length/position', type: 'good' },
                                { text: 'Encodes zones + target + actual', type: 'good' },
                                { text: 'Easily stackable (Dashboard-ready)', type: 'good' },
                            ].map((l, i) => (
                                <li key={i} className="flex items-center gap-2 text-[11px] text-stone-600 font-bold">
                                    <div className="w-1 h-1 rounded-full bg-emerald-500" />
                                    {l.text}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            </div>
        </ChartFrame>
    );
}

export default function AreWeOnScheduleLesson() {
    return (
        <LessonPage
            crossRefs={[
                { sectionId: 'perception', slug: 'preattentive', label: '1.1 — Pre-attentive: how radar charts encode across multiple channels simultaneously' },
                { sectionId: 'mechanics', slug: 'comparison', label: '2.1 — Comparison Charts: bullet charts as replacements for gauge charts' },
                { sectionId: 'lab', slug: 'full-lab', label: '3.5 — Full Lab: apply manipulation techniques to operational data' },
            ]}
        >
            <div className="space-y-6">
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    Operational and risk charts are purpose-built for specific analytical workflows: process monitoring, project management, conversion analysis, and multi-dimensional scoring. Unlike general-purpose comparison or distribution charts, each operational chart type carries strong structural assumptions about the data it visualizes. A Gantt chart assumes tasks have defined start dates and fixed durations. A control chart assumes a stable, repeating process with measurable variation. A funnel chart assumes a strictly sequential process where all items enter at the top stage. <strong>Misapplying these charts to data that violates their structural assumptions produces visualizations that look authoritative but actively mislead.</strong>
                </p>
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    The gauge chart — the half-circle dial with a needle pointing to a KPI value — is perhaps the most pervasive example of a chart optimized for aesthetics over information density. A gauge chart uses a semicircular area that could hold 5–10 bullet charts, yet encodes a single number in an angle encoding that ranks 5th in Cleveland & McGill's perceptual accuracy hierarchy. Stephen Few demonstrated that a bullet chart provides the same information (actual value, target, performance zones) in roughly 1/5 the space with superior perceptual accuracy. Gauge charts persist in dashboards not because they communicate more effectively but because they resemble familiar physical instruments and look appropriately "technical."
                </p>
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    Radar/spider charts present a similar problem: the polygon area is determined as much by axis ordering as by data values. Rotating the axes of a radar chart produces a different polygon shape and area — implying different "performance" — even though none of the values change. This means that radar chart comparisons between entities or time periods can be manipulated simply by choosing an axis order that makes the desired entity's polygon appear larger, without changing any underlying data. For multi-dimensional performance comparison, a <strong>small multiple bar chart approach</strong> (one bar per dimension, displayed in a grid) offers superior accuracy with zero axis-ordering sensitivity.
                </p>

                {/* Gauge vs Bullet */}
                <GaugeVsBulletChart />

                {/* Chart assumptions guide */}
                <div className="rounded-2xl bg-amber-50 border border-amber-200 p-6 shadow-sm border-l-4">
                    <div className="flex items-center gap-3 mb-6">
                        <TrendingUp size={20} className="text-amber-600" />
                        <p className="text-[11px] font-black text-amber-700 uppercase tracking-widest">
                            Structural Integrity Checklist
                        </p>
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-6">
                        {[
                            { icon: Target, chart: 'Gantt Chart', assumption: 'Tasks have defined start/end dates and fixed durations. Agile sprints with fluid scope violate this.' },
                            { icon: Zap, chart: 'Control Chart (SPC)', assumption: 'Process is stable and repeating with a historical baseline of ≥20 data points.' },
                            { icon: Info, chart: 'Funnel Chart', assumption: 'All items enter at stage 1 and progress forward-only. No re-entry or skipping.' },
                            { icon: Target, chart: 'Radar Chart', assumption: 'All axes share a common scale. Axis ordering is theoretically motivated, not arbitrary.' },
                        ].map((d, i) => (
                            <div key={i} className="space-y-1">
                                <div className="flex items-center gap-2">
                                    <d.icon size={14} className="text-amber-600" />
                                    <p className="font-black text-[12px] text-amber-900 uppercase tracking-tight">{d.chart}</p>
                                </div>
                                <p className="text-[13px] text-amber-800 leading-relaxed pl-5 font-medium opacity-90">{d.assumption}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <ChartFamilyLesson
                charts={charts}
                clevelandNote="Gauge and radar charts use angle as the primary encoding — one of the least accurately decoded channels in the Cleveland & McGill hierarchy. They are popular in executive dashboards despite their perceptual limitations, often because they resemble familiar physical instruments. Bullet charts (comparison family) outperform gauges on every measurable dimension of accuracy and information density."
            />
        </LessonPage>
    );
}
