import LessonPage from '../../layout/LessonPage';
import ChartFamilyLesson, { type ChartSpec } from './ChartFamilyLesson';
import {
    GanttMini,
    ControlChartMini,
    FunnelMini,
    RadarMini,
    GaugeMini,
} from '../../charts/demos/MiniCharts';

const charts: ChartSpec[] = [
    {
        slug: 'gantt',
        name: 'Gantt Chart',
        whenToUse: [
            'Project scheduling and timeline visualization showing task start dates, durations, and dependencies',
            'Resource allocation dashboards where overlapping tasks reveal capacity conflicts',
            'Communicating project status to stakeholders who need to see schedule at a glance',
        ],
        whenNotToUse: [
            'Very long time horizons with many tasks — granularity becomes unreadable',
            'Agile workflows where tasks are too fluid to represent as fixed bars',
            'When the critical path or task dependencies are the primary analytical focus — PERT/network is better',
        ],
        interpretationRisk: 'Gantt charts show planned duration but not completion percentage or quality. A task that appears "on time" as a full bar may be 0% complete internally. Without explicit progress overlays, Gantt charts are optimistic by default.',
        cognitiveRef: 'Pre-attentive: length, position (time)',
        ethicalRef: 'Risk: Planned vs. actual confusion',
        demo: <GanttMini />,
    },
    {
        slug: 'control-chart',
        name: 'Control Chart (SPC)',
        whenToUse: [
            'Statistical Process Control: monitoring whether a process is in control or exhibiting special-cause variation',
            'Manufacturing, quality assurance, or service delivery metrics tracked over time',
            'When distinguishing common-cause (random) variation from special-cause (assignable) variation is critical',
        ],
        whenNotToUse: [
            'Data that is not generated by a stable, repeating process',
            'Small samples where control limits cannot be reliably estimated (< 20 historical data points)',
            'Audiences who will interpret the ±3σ limits as performance targets rather than statistical boundaries',
        ],
        interpretationRisk: 'Control limits (±3σ) are statistical bounds for random variation, not performance targets. Communicating UCL/LCL to business audiences who interpret them as "acceptable range" goals corrupts the method — processes will be "managed to the limits" rather than continuously improved.',
        cognitiveRef: 'Pre-attentive: position, color (alert)',
        ethicalRef: 'Risk: Limits as targets',
        demo: <ControlChartMini />,
    },
    {
        slug: 'funnel',
        name: 'Funnel Chart',
        whenToUse: [
            'Sequential conversion or qualification processes where each stage filters the population from the previous',
            'Sales pipeline, marketing attribution, or user activation flows with defined sequential stages',
            'When identifying the stage with the largest drop-off is the primary analytical goal',
        ],
        whenNotToUse: [
            'Non-sequential processes where items can enter or exit at any stage',
            'When the total population at each stage is more important than the ratio between stages',
            'Processes with feedback loops — funnels imply strictly linear, forward-only flow',
        ],
        interpretationRisk: 'Funnel charts imply that all items enter at the top stage. In real pipelines, leads often enter mid-funnel, skip stages, or recycle through earlier stages. A funnel that makes a 30% overall conversion rate look visually impressive may hide a catastrophic early-stage drop-off.',
        cognitiveRef: 'Pre-attentive: length (width)',
        ethicalRef: 'Risk: Entry assumption',
        demo: <FunnelMini />,
    },
    {
        slug: 'radar',
        name: 'Radar / Spider Chart',
        whenToUse: [
            'Comparing performance profiles across 5–8 dimensions for 2–3 entities simultaneously',
            'Communicating trade-off profiles where no single axis dominates (e.g., risk-return across asset classes)',
            'Qualitative scoring rubrics where the "shape" of the profile is the primary insight',
        ],
        whenNotToUse: [
            'More than 3 overlapping polygons — the center fills with color and all shapes blur together',
            'When individual axis values need to be read precisely — the radial scale is hard to decode',
            'Axes with different units or scales that are not meaningfully comparable',
        ],
        interpretationRisk: 'The area of the radar polygon is extremely sensitive to axis ordering. Two identical datasets with axes reordered produce different polygon shapes and areas, suggesting different "performance" even though no values changed. Axis order should be theoretically motivated, not arbitrary.',
        cognitiveRef: 'Pre-attentive: area, shape',
        ethicalRef: 'Risk: Axis ordering changes area',
        demo: <RadarMini />,
    },
    {
        slug: 'gauge',
        name: 'Gauge / Dial Chart',
        whenToUse: [
            'Single KPI display in an executive dashboard where the metaphor of "progress toward a target" is intuitive',
            'When three qualitative performance zones (red/amber/green) need to be visible with the current value',
            'Physical monitoring contexts where users are already familiar with dial metaphors (speed, pressure)',
        ],
        whenNotToUse: [
            'Analytical reporting — gauges use space inefficiently and convey one number a bar could show better',
            'Multiple KPIs side-by-side — comparisons between gauges require mental effort that a table eliminates',
            'When historical trend matters — the gauge is a point-in-time reading with no trend context',
        ],
        interpretationRisk: 'Gauge charts show a single value in a half-circle that uses roughly 50% more space than a bullet chart showing the same information. They are frequently used in dashboards to make reports appear more sophisticated while actually reducing information density and analytical clarity.',
        cognitiveRef: 'Pre-attentive: angle, position',
        ethicalRef: 'Risk: Space-to-information inefficiency',
        demo: <GaugeMini />,
    },
];


// Gauge vs Bullet comparison chart
function GaugeVsBulletChart() {
    const value = 73, target = 80;

    // Gauge arc
    const cx = 50, cy = 48, r = 35;
    const arcAngle = (v: number) => ((v / 100) * Math.PI) + Math.PI; // left to right
    const toArcX = (a: number) => cx + r * Math.cos(a);
    const toArcY = (a: number) => cy + r * Math.sin(a);

    const startAngle = Math.PI; // 180°
    const valueAngle = arcAngle(value);
    const targetAngle = arcAngle(target);
    const aX = toArcX(valueAngle);
    const aY = toArcY(valueAngle);
    const bX = toArcX(startAngle);
    const bY = toArcY(startAngle);
    const endX = toArcX(0); // right side

    // Background arc (grey)
    const bgPath = `M ${bX} ${bY} A ${r} ${r} 0 0 1 ${endX} ${cy}`;
    // Value arc (green)
    const valPath = `M ${bX} ${bY} A ${r} ${r} 0 0 1 ${aX} ${aY}`;

    return (
        <div className="grid grid-cols-2 gap-6">
            <div>
                <p className="text-[10px] text-stone-400 font-bold text-center uppercase tracking-wider mb-2">
                    Gauge chart
                </p>
                <svg viewBox="0 0 100 60" className="w-full max-w-[140px] mx-auto">
                    {/* Background arc */}
                    <path d={bgPath} fill="none" stroke="#e7e5e4" strokeWidth={10} strokeLinecap="round" />
                    {/* Green arc */}
                    <path d={valPath} fill="none" stroke="#059669" strokeWidth={10} strokeLinecap="round" />
                    {/* Target line */}
                    <line
                        x1={cx + (r - 8) * Math.cos(targetAngle)}
                        y1={cy + (r - 8) * Math.sin(targetAngle)}
                        x2={cx + (r + 2) * Math.cos(targetAngle)}
                        y2={cy + (r + 2) * Math.sin(targetAngle)}
                        stroke="#1e293b" strokeWidth={2} />
                    <text x={cx} y={cy + 8} fill="#059669" fontSize={12} textAnchor="middle" fontWeight={900}>{value}%</text>
                    <text x={cx} y={cy + 17} fill="#a8a29e" fontSize={5} textAnchor="middle">Target: {target}%</text>
                </svg>
                <div className="space-y-1 mt-2">
                    <p className="text-[10px] text-red-600 text-center">Uses ~60% more space</p>
                    <p className="text-[10px] text-red-600 text-center">Encodes 1 number (angle)</p>
                    <p className="text-[10px] text-red-600 text-center">No trend context</p>
                </div>
            </div>
            <div>
                <p className="text-[10px] text-stone-400 font-bold text-center uppercase tracking-wider mb-2">
                    Bullet chart
                </p>
                <svg viewBox="0 0 100 60" className="w-full max-w-[140px] mx-auto">
                    {/* Qualitative ranges */}
                    <rect x={10} y={20} width={80} height={18} fill="#e7e5e4" rx={2} />
                    <rect x={10} y={20} width={64} height={18} fill="#d1d5db" rx={2} />
                    <rect x={10} y={20} width={48} height={18} fill="#9ca3af" rx={2} />
                    {/* Actual bar */}
                    <rect x={10} y={24} width={(value / 100) * 80} height={10} fill="#059669" rx={2} />
                    {/* Target line */}
                    <line x1={10 + (target / 100) * 80} y1={17} x2={10 + (target / 100) * 80} y2={41}
                        stroke="#1e293b" strokeWidth={2.5} />
                    <text x={10 + (value / 100) * 80 + 3} y={32} fill="#a8a29e" fontSize={5}>{value}%</text>
                    <text x={10 + (target / 100) * 80 - 2} y={14} fill="#1e293b" fontSize={5} textAnchor="middle">Target</text>
                    <text x={10} y={52} fill="#a8a29e" fontSize={5}>0</text>
                    <text x={90} y={52} fill="#a8a29e" fontSize={5} textAnchor="end">100</text>
                </svg>
                <div className="space-y-1 mt-2">
                    <p className="text-[10px] text-brand text-center">Uses ~40% less space</p>
                    <p className="text-[10px] text-brand text-center">Encodes value + target + zones</p>
                    <p className="text-[10px] text-brand text-center">Aligns with position encoding</p>
                </div>
            </div>
        </div>
    );
}

export default function OperationalLesson() {
    return (
        <LessonPage
            crossRefs={[
                { sectionId: 'perception', slug: 'preattentive', label: '1.1 — Pre-attentive: how radar charts encode across multiple channels simultaneously' },
                { sectionId: 'mechanics', slug: 'comparison', label: '2.1 — Comparison Charts: bullet charts as replacements for gauge charts' },
                { sectionId: 'lab', slug: 'full-lab', label: '3.5 — Full Lab: apply manipulation techniques to operational data' },
            ]}
        >
            <div className="space-y-6">
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    Operational and risk charts are purpose-built for specific analytical workflows: process monitoring, project management, conversion analysis, and multi-dimensional scoring. Unlike general-purpose comparison or distribution charts, each operational chart type carries strong structural assumptions about the data it visualizes. A Gantt chart assumes tasks have defined start dates and fixed durations. A control chart assumes a stable, repeating process with measurable variation. A funnel chart assumes a strictly sequential process where all items enter at the top stage. <strong>Misapplying these charts to data that violates their structural assumptions produces visualizations that look authoritative but actively mislead.</strong>
                </p>
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    The gauge chart — the half-circle dial with a needle pointing to a KPI value — is perhaps the most pervasive example of a chart optimized for aesthetics over information density. A gauge chart uses a semicircular area that could hold 5–10 bullet charts, yet encodes a single number in an angle encoding that ranks 5th in Cleveland & McGill's perceptual accuracy hierarchy. Stephen Few demonstrated that a bullet chart provides the same information (actual value, target, performance zones) in roughly 1/5 the space with superior perceptual accuracy. Gauge charts persist in dashboards not because they communicate more effectively but because they resemble familiar physical instruments and look appropriately "technical."
                </p>
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    Radar/spider charts present a similar problem: the polygon area is determined as much by axis ordering as by data values. Rotating the axes of a radar chart produces a different polygon shape and area — implying different "performance" — even though none of the values change. This means that radar chart comparisons between entities or time periods can be manipulated simply by choosing an axis order that makes the desired entity's polygon appear larger, without changing any underlying data. For multi-dimensional performance comparison, a <strong>small multiple bar chart approach</strong> (one bar per dimension, displayed in a grid) offers superior accuracy with zero axis-ordering sensitivity.
                </p>

                {/* Gauge vs Bullet */}
                <div className="bg-white rounded-xl border border-stone-200 p-5 space-y-3">
                    <p className="text-[11px] font-bold text-stone-400 uppercase tracking-wider">
                        Gauge vs. bullet chart: same KPI, radically different space efficiency
                    </p>
                    <GaugeVsBulletChart />
                    <p className="text-[12px] text-stone-400 leading-relaxed">
                        Both charts show a KPI of 73% against a target of 80%. The bullet chart encodes actual value, target, and three qualitative performance zones in 40% less space, using the more accurate position encoding instead of angle. The gauge chart uses the familiar dial metaphor at a severe cost in information density.
                    </p>
                </div>

                {/* Chart assumptions guide */}
                <div className="rounded-xl bg-amber-50 border border-amber-200 p-5">
                    <p className="text-[11px] font-bold text-amber-700 uppercase tracking-wider mb-3">
                        Structural assumptions that must hold for operational charts to be valid
                    </p>
                    <div className="space-y-2">
                        {[
                            { chart: 'Gantt chart', assumption: 'Tasks have defined start/end dates and fixed durations. Agile sprints with fluid scope violate this.' },
                            { chart: 'Control chart (SPC)', assumption: 'Process is stable and repeating with a historical baseline of ≥20 data points for control limit estimation.' },
                            { chart: 'Funnel chart', assumption: 'All items enter at stage 1 and progress forward-only through a fixed sequence. No re-entry or skipping.' },
                            { chart: 'Radar chart', assumption: 'All axes share a meaningful common scale. Axis ordering is theoretically motivated, not arbitrary.' },
                            { chart: 'Gauge / dial', assumption: 'A single KPI value at a moment in time is sufficient for the decision. No trend context is needed.' },
                        ].map((d, i) => (
                            <div key={i} className="text-[12px] space-y-0.5">
                                <p className="font-bold text-amber-900">{d.chart}</p>
                                <p className="text-amber-800 leading-relaxed pl-3">{d.assumption}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            <ChartFamilyLesson
                charts={charts}
                clevelandNote="Gauge and radar charts use angle as the primary encoding — one of the least accurately decoded channels in the Cleveland & McGill hierarchy. They are popular in executive dashboards despite their perceptual limitations, often because they resemble familiar physical instruments. Bullet charts (comparison family) outperform gauges on every measurable dimension of accuracy and information density."
            />
        </LessonPage>
    );
}
