import LessonPage from '../../layout/LessonPage';
import ChartFamilyLesson, { type ChartSpec } from './ChartFamilyLesson';
import {
    GanttMini,
    ControlChartMini,
    FunnelMini,
    RadarMini,
    GaugeMini,
} from '../../charts/demos/MiniCharts';

const charts: ChartSpec[] = [
    {
        slug: 'gantt',
        name: 'Gantt Chart',
        whenToUse: [
            'Project scheduling and timeline visualization showing task start dates, durations, and dependencies',
            'Resource allocation dashboards where overlapping tasks reveal capacity conflicts',
            'Communicating project status to stakeholders who need to see schedule at a glance',
        ],
        whenNotToUse: [
            'Very long time horizons with many tasks — granularity becomes unreadable',
            'Agile workflows where tasks are too fluid to represent as fixed bars',
            'When the critical path or task dependencies are the primary analytical focus — PERT/network is better',
        ],
        interpretationRisk: 'Gantt charts show planned duration but not completion percentage or quality. A task that appears "on time" as a full bar may be 0% complete internally. Without explicit progress overlays, Gantt charts are optimistic by default.',
        cognitiveRef: 'Pre-attentive: length, position (time)',
        ethicalRef: 'Risk: Planned vs. actual confusion',
        demo: <GanttMini />,
    },
    {
        slug: 'control-chart',
        name: 'Control Chart (SPC)',
        whenToUse: [
            'Statistical Process Control: monitoring whether a process is in control or exhibiting special-cause variation',
            'Manufacturing, quality assurance, or service delivery metrics tracked over time',
            'When distinguishing common-cause (random) variation from special-cause (assignable) variation is critical',
        ],
        whenNotToUse: [
            'Data that is not generated by a stable, repeating process',
            'Small samples where control limits cannot be reliably estimated (< 20 historical data points)',
            'Audiences who will interpret the ±3σ limits as performance targets rather than statistical boundaries',
        ],
        interpretationRisk: 'Control limits (±3σ) are statistical bounds for random variation, not performance targets. Communicating UCL/LCL to business audiences who interpret them as "acceptable range" goals corrupts the method — processes will be "managed to the limits" rather than continuously improved.',
        cognitiveRef: 'Pre-attentive: position, color (alert)',
        ethicalRef: 'Risk: Limits as targets',
        demo: <ControlChartMini />,
    },
    {
        slug: 'funnel',
        name: 'Funnel Chart',
        whenToUse: [
            'Sequential conversion or qualification processes where each stage filters the population from the previous',
            'Sales pipeline, marketing attribution, or user activation flows with defined sequential stages',
            'When identifying the stage with the largest drop-off is the primary analytical goal',
        ],
        whenNotToUse: [
            'Non-sequential processes where items can enter or exit at any stage',
            'When the total population at each stage is more important than the ratio between stages',
            'Processes with feedback loops — funnels imply strictly linear, forward-only flow',
        ],
        interpretationRisk: 'Funnel charts imply that all items enter at the top stage. In real pipelines, leads often enter mid-funnel, skip stages, or recycle through earlier stages. A funnel that makes a 30% overall conversion rate look visually impressive may hide a catastrophic early-stage drop-off.',
        cognitiveRef: 'Pre-attentive: length (width)',
        ethicalRef: 'Risk: Entry assumption',
        demo: <FunnelMini />,
    },
    {
        slug: 'radar',
        name: 'Radar / Spider Chart',
        whenToUse: [
            'Comparing performance profiles across 5–8 dimensions for 2–3 entities simultaneously',
            'Communicating trade-off profiles where no single axis dominates (e.g., risk-return across asset classes)',
            'Qualitative scoring rubrics where the "shape" of the profile is the primary insight',
        ],
        whenNotToUse: [
            'More than 3 overlapping polygons — the center fills with color and all shapes blur together',
            'When individual axis values need to be read precisely — the radial scale is hard to decode',
            'Axes with different units or scales that are not meaningfully comparable',
        ],
        interpretationRisk: 'The area of the radar polygon is extremely sensitive to axis ordering. Two identical datasets with axes reordered produce different polygon shapes and areas, suggesting different "performance" even though no values changed. Axis order should be theoretically motivated, not arbitrary.',
        cognitiveRef: 'Pre-attentive: area, shape',
        ethicalRef: 'Risk: Axis ordering changes area',
        demo: <RadarMini />,
    },
    {
        slug: 'gauge',
        name: 'Gauge / Dial Chart',
        whenToUse: [
            'Single KPI display in an executive dashboard where the metaphor of "progress toward a target" is intuitive',
            'When three qualitative performance zones (red/amber/green) need to be visible with the current value',
            'Physical monitoring contexts where users are already familiar with dial metaphors (speed, pressure)',
        ],
        whenNotToUse: [
            'Analytical reporting — gauges use space inefficiently and convey one number a bar could show better',
            'Multiple KPIs side-by-side — comparisons between gauges require mental effort that a table eliminates',
            'When historical trend matters — the gauge is a point-in-time reading with no trend context',
        ],
        interpretationRisk: 'Gauge charts show a single value in a half-circle that uses roughly 50% more space than a bullet chart showing the same information. They are frequently used in dashboards to make reports appear more sophisticated while actually reducing information density and analytical clarity.',
        cognitiveRef: 'Pre-attentive: angle, position',
        ethicalRef: 'Risk: Space-to-information inefficiency',
        demo: <GaugeMini />,
    },
];

export default function OperationalLesson() {
    return (
        <LessonPage
            crossRefs={[
                { sectionId: 'perception', slug: 'preattentive', label: '1.1 — Pre-attentive: how radar charts encode across multiple channels simultaneously' },
                { sectionId: 'mechanics', slug: 'comparison', label: '2.1 — Comparison Charts: bullet charts as replacements for gauge charts' },
                { sectionId: 'lab', slug: 'full-lab', label: '3.5 — Full Lab: apply manipulation techniques to operational data' },
            ]}
        >
            <div className="prose prose-stone max-w-none">
                <p className="text-[15px] text-stone-600 leading-relaxed">
                    Operational and risk charts are purpose-built for specific analytical workflows: process
                    monitoring, project management, conversion analysis, and multi-dimensional scoring. They
                    tend to be domain-specific and carry strong implicit assumptions about the process being
                    visualized. <strong>The key risk is misapplying these charts to data that violates their
                        structural assumptions</strong> — a Gantt for an Agile sprint, a control chart with too few
                    observations, or a funnel for a non-sequential process all produce charts that look valid
                    but mislead.
                </p>
            </div>

            <ChartFamilyLesson
                charts={charts}
                clevelandNote="Gauge and radar charts use angle as the primary encoding — one of the least accurately decoded channels in the Cleveland & McGill hierarchy. They are popular in executive dashboards despite their perceptual limitations, often because they resemble familiar physical instruments. Bullet charts (comparison family) outperform gauges on every measurable dimension of accuracy and information density."
            />
        </LessonPage>
    );
}
